### PR TITLE
engine: server: log: fix log off command not disabling logging to console (fixes #1340)

### LINKED ISSUE #1340: sv_log is broken

### PR DESCRIPTION
**Pull request by jeefo**

### CODE REVIEW

**Review by a1batross — APPROVED** [review]

**Review by a1batross — COMMENTED** [review]
Disapproved. Review again later.

File: engine/server/sv_log.c [hunk 1]
```diff
@@ -169,11 +169,21 @@ void SV_SetLogAddress_f( void )
...
+
+		Con_Printf( "logaddress: disabled.\n" );
+
+		return;
+	}
+
 	if( Cmd_Argc() != 3 )
 	{
-		Con_Printf( "logaddress: usage\nlogaddress ip port\n" );
+		Con_Printf( "logaddress: usage\nlogaddress < ip port | off >\n" );
```
Comment (a1batross) [inline engine/server/sv_log.c:184]: While you're at it, replace usage line by more simple and common: `S_USAGE "logaddress < IP port | off >"`

Other than this, I'm fine with these changes.

**Review by a1batross — CHANGES_REQUESTED** [review]

**Review by a1batross — APPROVED** [review]
